### ISSUE TITLE
Vim(let):E687: Less targets than List items

### ISSUE THREAD

**Issue by h0adp0re** [kristijanhusak/vim-create-pr#3]
Using a custom Bitbucket server URL I'm getting this error.

```
Vim(let):E687: Less targets than List items
```

**Comment by kristijanhusak** [comment]
Can you give me the custom url you are using? Just replace the main domain name with domething dummy.

**Comment by h0adp0re** [comment]
Sure, here it is, with minor censoring.
```
https://stash.site.local/projects/PROJECT/repos/{{repository}}/pull-requests?create&targetBranch=refs%2Fheads%2Fdevelop&sourceBranch={{branch_name}}&targetRepoId=783
```

**Comment by kristijanhusak** [comment]
Can you also please give me the output of this command from repo:

```
git config --get remote.origin.url
```
Just please censor the same things like in the url above so I can match things.

I'm most likely not parsing the values properly, so any info is really helpful.

**Comment by h0adp0re** [comment]
Yup, same things censored here:
```
ssh://git@stash.site.local:7999/project/repository.git
```
Note that `project` is the same thing as `PROJECT` in my previous comment and `repository` is the same thing that should be in place of `{{repository}}` in the previous comment.

**Comment by kristijanhusak** [comment]
Thanks. Pull latest changes and give it another test. Should be working now.

**Comment by h0adp0re** [comment]
Now it's working, thanks!
